export const API = 'http://localhost:8000/'
export const APIusers = 'http://localhost:8000/users'
export const APIservices = 'http://localhost:8000/services'
export const APIcomments = 'http://localhost:8000/comments'
export const APIfeedbacks = 'http://localhost:8000/feedbacks'
